#!/usr/bin/env python3

from sqlalchemy import Column, ForeignKey, Integer, String, Boolean, Date
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

from sqlalchemy import create_engine

engine = create_engine('sqlite:///nba.db')

Base = declarative_base()


class Team(Base):
    __tablename__ = 'team'
    id = Column(String(3), primary_key=True)
    location = Column(String(30), nullable=False)
    team = Column(String(30), nullable=False)

class Game(Base):
    __tablename__ = 'game'
    id = Column(Integer, primary_key=True)
    team_id = Column(Integer, ForeignKey('team.id'))
    home = Column(Boolean, default=True, nullable=False)
    opponent = Column(String(3), nullable=False)
    date = Column(Date(), nullable=False)

def buildTeams():
    Base.metadata.create_all(engine)

teams = ('ATL', 'BOS', 'NJN', 'CHA', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NOH', 'NYK', 'OKC', 'ORL', 'PHI', 'PHO', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS')

url="https://www.basketball-reference.com/teams/SAS/1990_games.html"
