# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('contract_year', models.PositiveSmallIntegerField()),
                ('base_compensation', models.PositiveIntegerField()),
                ('guarantee_percentage', models.PositiveSmallIntegerField()),
                ('option', models.CharField(choices=[(b'N', b'-'), (b'T', b'Team'), (b'P', b'Player')], max_length=1)),
                ('contract_type', models.CharField(choices=[(b'RS', b'Rookie Scale'), (b'RSE', b'Rookie Scale Extension'), (b'VET', b'Veteran'), (b'VE', b'Veteran Extension')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('position', models.CharField(choices=[(b'C', b'C'), (b'PF', b'PF'), (b'SF', b'SF'), (b'SG', b'SG'), (b'PG', b'PG')], max_length=2)),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('wingspan', models.PositiveSmallIntegerField()),
                ('handwidth', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('abbv', models.CharField(max_length=3)),
                ('logo', models.ImageField(upload_to=b'logos/%Y/')),
            ],
        ),
        migrations.AddField(
            model_name='contracthistory',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Team'),
        ),
        migrations.AddField(
            model_name='contract',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Player'),
        ),
    ]
