# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_team_conference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='abbv',
        ),
        migrations.RemoveField(
            model_name='team',
            name='conference',
        ),
    ]
