# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(choices=[(b'East', b'East'), (b'West', b'West')], default='West', max_length=4),
            preserve_default=False,
        ),
    ]
